# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly" # How often to check for updates

  # Configuration for Composer
  - package-ecosystem: "composer"
    directory: "/" # Location of composer.json
    schedule:
      interval: "weekly" # How often to check for updates
allow:
  - dependency-type: "direct"
    update-types: ["security"]
open-pull-requests-limit: 10
